= Zheng Jie
:page-description: Zheng Jie
:page-layout: home

Over the past decade developing Web applications while working in startup companies
through to medium-size institutions. Most of them are data-intensive applications.
In computer science, I am interested in algorithms and data structures.
Believe in efficient software design.

[quote, Bjarne Stroustrup]
Efficiency is not just running fast or running bigger programs,
it’s also running using less resources.

I occasionally write posts in link:/archive/en[English]
or link:/archive/zh[Chinese], mostly technical.

I am https://github.com/prettykingking[prettykingking] on Github.
You could contact me at *prettykingking@live.com*.


== Projects

https://github.com/prettykingking/snowflake[Snowflake]:: GUID(Globally Unique ID)
Generation Service written in Golang.


== Reading

I collected links here as my bookmarks. They are all at public domains.
It's very convenient for me to look up at any time.
Using the browser's Find +++<i class="bi bi-search"></i>+++
can quickly jump to links. Look up link:/bookmarks[Bookmarks] only if you are
interested.

'''
