= Bash - The quick guide
Jie Zheng <prettykingking@live.com>
:revdate: September 1, 2023
:page-lang: en
:page-layout: post_en
:page-category: Shell
:page-description: Quickly find recipes to resolve shell tasks.

BASH is an acronym for **B**ourne **A**gain Shell.
It is the default shell in most Linux distributions. So use it well can be a
time-saving skill.

For full reference, check
https://www.gnu.org/software/bash/manual/bash.html[GNU Bash Manual].

== Command line interaction

=== Moving

* kbd:[Control+A] Go to the beginning of the line you are currently typing on.
* kbd:[Control+E] Go to the end of the line you are currently typing on.
* kbd:[Control+F] Move forward a character.
* kbd:[Control+B] Move back a character.
* kbd:[Meta+F] Move cursor forward one word on the current line.
* kbd:[Meta+B] Move cursor backward one word on the current line.
* kbd:[Control+C] Kill whatever you are running.
* kbd:[Control+D] Exit the current shell.

=== Editing

* kbd:[Tab] Auto-complete files and folder names.
* kbd:[Control+W] Delete the word before the cursor.
* kbd:[Control+K] Clear the line after the cursor.
* kbd:[Control+T] Swap the last two characters before the cursor.
* kbd:[Meta+T] Swap the last two words before the cursor.
* kbd:[Control+L] Clears the Screen, similar to the clear command.
* kbd:[Control+U] Clears the line before the cursor position.
If you are at the end of the line, clears the entire line.
* kbd:[Control+H] Same as backspace.
* kbd:[Control+Z] Puts whatever you are running into a suspended background process.
`fg` restores it.

=== Searching in the history

* kbd:[Control+R] Searches backworkd through the history.
* kbd:[Control+S] Searches forward through the history.


== Scripting

Check https://devhints.io/bash[Cheatsheet] for syntax,

More detailed tutorial:

* https://devdocs.io/bash/[Bash docs]
* https://aaltoscicomp.github.io/linux-shell/[Shell tutorial]
* https://explainshell.com[Explain shell]

=== Font colors

Common colors

----
Black        0;30     Dark Gray    1;30
Red          0;31     Light Red    1;31
Green        0;32     Light Green  1;32
Brown/Orange 0;33     Yellow       1;33
Blue         0;34     Light Blue   1;34
Purple       0;35     Light Purple 1;35
Cyan         0;36     Light Cyan   1;36
Light Gray   0;37     White        1;37

No Color     0

Bold Red           1;31
High Intensity Red 0;91
----

Print RED in shell

----
printf "\033[0;91mRED\033[0m\n"
----


=== Read file line by line

IFS stands for internal field separator or input field separator.
The default value is a space, a tab, a newline feed.

[source,sh]
----
while IFS="" read -r line; do
    echo $line
done < README.txt
----


=== Generate random string

Random string with 12 length

----
dd if=/dev/urandom count=1 2> /dev/null | base64 -i - | cut -c -12 -
----


=== Here doc for arbitrary text

----
cat <<EOF | tee file.txt
line 1
line 2
EOF
----


=== Keep runing after logging off

The `&` symbol at the end send it to the background.

----
nohup [CMD] > nohup.out &
----

Unlike `nohup`, `disown` is used after you started a process.

----
disown [PID]
----

=== Parse CLI arguments

The following snippet implements CLI arguments parsing. Options usually start
with a dash, but arguments is position based. It should be useful for most
scenarios.

[%linenums,sh]
----
# usage: script.sh -o1 abc xyz
opts_count=0
args_count=0
args=()
dry_run=0

# define options here
opt1=''

while :; do
  case "${1-}" in
  -h | --help)
    echo 'help message'
    exit 0
    ;;

  # parse options
  --dry-run)
    dry_run=1
    ;;

  -o1 | --opt1)
    opt1="${2-}"

    (( opts_count += 1 ))
    shift
    ;;

  -?*)
    echo "unrecognized option"
    exit 0
    ;;

  *)
    args+=("${1-}")

    if [[ -z "${1-}" ]]; then
      break
    fi
    ;;
  esac

  if [[ -n "${1-}" ]]; then
    shift
  fi
done

# default value for arguments
arg1=''

# parse args
for arg in "${args[@]}"; do
  if [[ -n "$arg" ]]; then
    (( args_count += 1 ))

    # define positional arguments here
    if (( args_count == 1 )); then
      arg1="$arg"
    fi
  fi
done

if (( opts_count == 0 && args_count == 0 )); then
  echo "no options or aguments"
fi
----

== FAQ

=== Single quotes or double quotes?

echo string can be included using single quotes or double quotes.
But double quotes is preferred, because single quotes can't match end of file.
When echo string using single quotes, there must be a semicolon at the end
`echo 'Little King';`

=== Single square brackets or double square brackets?

Please refer to http://mywiki.wooledge.org/BashFAQ/031[Greg's Wiki]

=== Can I do a spinner in Bash?

Please refer to http://mywiki.wooledge.org/BashFAQ/034[Greg's Wiki].

