= Bash - The quick guide
Jie Zheng <prettykingking@live.com>
:revdate: September 1, 2023
:page-lang: en
:page-layout: post_en
:page-category: Shell
:page-description: Quickly find recipes to resolve shell tasks.

BASH is an acronym for **B**ourne **A**gain Shell.
It is the default shell in most Linux distributions. So use it well can be a
time-saving skill.

For full reference, check
https://www.gnu.org/software/bash/manual/bash.html[GNU Bash Manual].

== Command line interaction

=== Moving

* kbd:[Control+A] Go to the beginning of the line you are currently typing on.
* kbd:[Control+E] Go to the end of the line you are currently typing on.
* kbd:[Control+F] Move forward a character.
* kbd:[Control+B] Move back a character.
* kbd:[Meta+F] Move cursor forward one word on the current line.
* kbd:[Meta+B] Move cursor backward one word on the current line.
* kbd:[Control+C] Kill whatever you are running.
* kbd:[Control+D] Exit the current shell.

=== Editing

* kbd:[Tab] Auto-complete files and folder names.
* kbd:[Control+W] Delete the word before the cursor.
* kbd:[Control+K] Clear the line after the cursor.
* kbd:[Control+T] Swap the last two characters before the cursor.
* kbd:[Meta+T] Swap the last two words before the cursor.
* kbd:[Control+L] Clears the Screen, similar to the clear command.
* kbd:[Control+U] Clears the line before the cursor position.
If you are at the end of the line, clears the entire line.
* kbd:[Control+H] Same as backspace.
* kbd:[Control+Z] Puts whatever you are running into a suspended background process.
`fg` restores it.

=== Searching in the history

* kbd:[Control+R] Searches backworkd through the history.
* kbd:[Control+S] Searches forward through the history.


== Scripting

Check https://devhints.io/bash[Cheatsheet] for syntax,

More detailed tutorial:

* https://devdocs.io/bash/[Bash docs]
* https://aaltoscicomp.github.io/linux-shell/[Shell tutorial]
* https://explainshell.com[Explain shell]

=== Font colors

Common colors

----
Black        0;30     Dark Gray    1;30
Red          0;31     Light Red    1;31
Green        0;32     Light Green  1;32
Brown/Orange 0;33     Yellow       1;33
Blue         0;34     Light Blue   1;34
Purple       0;35     Light Purple 1;35
Cyan         0;36     Light Cyan   1;36
Light Gray   0;37     White        1;37

No Color     0

Bold Red           1;31
High Intensity Red 0;91
----

Print RED in shell

----
printf "\033[0;91mRED\033[0m\n"
----

=== Generate random string

Random string with 12 length

[source,sh]
----
dd if=/dev/urandom count=1 2> /dev/null | base64 -i - | cut -c -12 -
----

=== Keep runing after logging off

The `&` symbol at the end send it to the background.

[source,sh,subs="macros+"]
----
nohup [+++<var>CMD</var>+++] > nohup.out &
----

Unlike `nohup`, `disown` is used after you started a process.

[source,sh,subs="macros+"]
----
disown [+++<var>PID</var>+++]
----


== FAQ

=== Single quotes or double quotes?

echo string can be included using single quotes or double quotes.
But double quotes is preferred, because single quotes can't match end of file.
When echo string using single quotes, there must be a semicolon at the end
`echo 'Little King';`

=== Single square brackets or double square brackets?

Please refer to http://mywiki.wooledge.org/BashFAQ/031[Greg's Wiki]

=== Can I do a spinner in Bash?

Please refer to http://mywiki.wooledge.org/BashFAQ/034[Greg's Wiki].

