= 贷款的实际年利率
Jie Zheng <prettykingking@live.com>
:revdate: January 30, 2024
:sectnums:
:page-lang: zh
:page-layout: post_zh
:page-category: 金融财务
:page-tags: [金融, 贷款]
:page-description: 计算与衡量贷款的实际年利率

近期计划购车，对于意向车型有能力全款购车，但如果支付贷款费率，所获得时间收益和风险收益对自己合理划算，
也会选择贷款。此前从未有过需要贷款的大额消费支出，对贷款知之甚少，因而查阅了很多相关介绍。
很多文章都是零零散散缺乏要点，没能使我解惑。
有的只简单提了概念，没有计算推导。有的给出了计算推导，却又不对带入系数作出解释。
由于自身需要，也想多了解一些金融常识，遂想写个记录。

名词定义都来自于公开百科或行业术语，在确保推导公式准确的前提下，
为了方便更直观地理解不同还款方式的利弊，公式中尽可能使用整数和整数运算。


== 还款方式

还款方式通常有等额本息、等额本金、等本等息，下面分别进行解释。

推导公式中所用到的标识及其含义：

* latexmath:[P] 每月应还数额
* latexmath:[A] 贷款数额
* latexmath:[r] 月利率
* latexmath:[n] 月数期限
* latexmath:[i] 当月利息

=== 等额本息

每月还款数额相同，本金逐月增多，利息逐月减少。此方式由于归还本金较慢，资金占用周期较长，
所以利息相对较多。每月还款数额公式：

[latexmath]
++++
P = A \left( \frac {r(1 + r)^n} {(1 + r)^n - 1} \right)
++++

贷款 10 万，月利率 1%，期限 3 年（36 个月）。计算得出：

* 每月应还数额 3321.43 元，包含本金和利息。
* 每月应还利息 latexmath:[=] 剩余未还本金 latexmath:[\times] 月利率。
第一个月利息为 1000，第二个月为 976.79，以此类推。
* 每月应还本金 latexmath:[=] 3321 latexmath:[-] 每月应还利息。
第一个月本金为 2321.43，第二个月本金为 2344.21，以此类推。
* 总还款数额约为 11.96 万，其中利息约为 1.96 万。

=== 等额本金

每月偿还本金相同，利息与等额本息相同，逐月减少。此方式在还款初期压力较大，但随着时间推移，
每月还款数额减少。每月还款数额公式：

[latexmath]
++++
P = \frac {A} {n} + i
++++

贷款 10 万，月利率 1%，期限 3 年（36 个月）。计算得出：

* 每月应还本金约为 2778 元，10 万 latexmath:[/] 36。
* 每月应还利息 latexmath:[=] 剩余未还本金 latexmath:[\times] 月利率。
第一个月利息为 1000，第二个月利息为 990，以此类推。
* 总还款数额约为 11.85 万，其中利息约为 1.85 万，同期限相比等额本息略低。


=== 等本等息

等本等息常见于车贷。车贷所谓的费率就是等本等息，计算也很简单，还款期限内，
每个还款周期都按全额贷款计算利息。每月还款数额公式：

[latexmath]
++++
P = \frac {A} {n} + (A * r)
++++

贷款 10 万，月利率 1%，期限 3 年（36 个月）。计算得出：

* 每月应还本金 2778 元，10 万 latexmath:[/] 36。
* 每月应还利息 1000 元，10 万 latexmath:[\times] 0.01。
* 总还款数额约为 13.6 万元，其中利息约为 3.6 万元。

==== 折合年化利率

车贷通常以费率的形式向消费者呈现，伴随着折合后的年利率。费率就是一种等本等息的形式，
将利息作为服务费、手续费等，4S 店常见的金融手续费就是典型。
但很多汽车销售公司不会告诉消费者实际年利率，使消费者误将较低的费率当作年利率，与其它机构的
金融产品进行比较，导致支付最终更多的利息。

费率折合成年利率，涉及到一个重要的参数叫年金现值系数
(https://www.investopedia.com/terms/p/pvifa.asp[PVIFA])，根据年金现值系数可以准确算出
折合年化利率。想要深入推导的同学，可以查找相关资料。我非金融专业，阐述背后逻辑难免会出纰漏，
还请谅解。

但对于消费者判断贷款产品的利弊，需要知道折合年化利率，有一个简便的方法。将贷款费率与固定系数
1.9 相乘，即得出大约年化利率。固定系数取值为 1.9，是因为通过精确计算，
年化利率与费率的比例约为 (1.8 - 2.0) 比 1，参考link:#further-reading[延伸阅读]。

== 总结

等本等息所支付利息是最高的，其次是等额本息、等额本金。除了以上三种方式外，还有一种先息后本的还款方式，
利率很高，适用于短期贷款。先息后本的利息计算非常简单，固定本金与固定利率，计算出每个月的固定应还款数额，
期限到期后，一并归还本金。

综上所述，在需要贷款时，多对比不同金融平台给出的利率，根据个人经济情况选择适合自己的还款方式。

[#further-reading]
== 延伸阅读

* https://www.moneyhero.com.hk/blog/zh/月平息-低唔一定抵-實際年利率-apr-最實際[月平息利息及年利率計算]
* https://www.moneyhero.com.hk/blog/zh/提早還款有著數-貸款前要明白利息的78法則[贷款利息 78 法则]

