= 贷款的实际年利率
Jie Zheng <prettykingking@live.com>
:revdate: January 30, 2024
:sectnums:
:page-lang: zh
:page-layout: post_zh
:page-category: 金融
:page-description: 计算与衡量贷款的实际年利率

计划近期购车，对于意向车型有能力全款购车，但如果支付贷款费率，所获得时间成本和风险成本
对自己合理划算，也会选择贷款。
此前从未有过需要贷款的大额消费支出，对贷款知之甚少，因而搜罗了很多相关介绍。
但感觉都零零散散缺乏要点，没能使我解惑。
有的只简单提了概念，没有计算推导。有的给出了计算推导，却又不对带入数字作出解释。
由于自身需要，也想多了解一些金融常识，才有了这篇总结。

名词定义都来自于公开百科或行业术语，在确保推导公式准确的前提下，
为了方便更直观理解和衡量不同方式的利弊，公式中尽可能使用整数和整数运算。


== 还款方式

还款方式通常有等额本息、等额本金、等本等息，下面分别进行解释。

推导公式中所用到的标识及其含义：

* latexmath:[P] 每月应还数额
* latexmath:[A] 贷款数额
* latexmath:[r] 月利率
* latexmath:[m] 月数期限
* latexmath:[i] 当月利息

=== 等额本息

每月还款数额相同，本金逐月增多，利息逐月减少。此方式由于归还本金较慢，资金占用周期较长，
所以利息相对较多。每月还款数额公式：

[latexmath]
++++
P = A \left( \frac {r(1 + r)^m} {(1 + r)^m - 1} \right)
++++

贷款 10 万，月利率 1%，期限 3 年（36 个月）。计算得出：

* 每月应还数额 3321 元，包含本金和利息。
* 每月应还利息 latexmath:[=] 剩余未还本金 latexmath:[\times] 月利率。
* 每月应还本金 latexmath:[=] 3321 latexmath:[-] 每月应还利息。
* 总还款数额约为 11.9 万，其中利息约为 1.9 万。

=== 等额本金

每月偿还本金相同，利息与等额本息相同，逐月减少。此方式在还款初期压力较大，但随着时间推移，
每月还款数额减少。每月还款数额公式：

[latexmath]
++++
P = \frac {A} {m} + i
++++

贷款 10 万，月利率 1%，期限 3 年（36 个月）。计算得出：

* 每月应还本金约为 2778 元，10 万 latexmath:[/] 36。
* 每月应还利息 latexmath:[=] 剩余未还本金 latexmath:[\times] 月利率。
第一个月利息为 1000，第二个月利息为 990，以此类推。


=== 等本等息

等本等息常见于车贷。车贷所谓的费率就是等本等息，计算也很简单，还款期限内，
每个还款周期都按全额贷款计算利息。每月还款数额公式：

[latexmath]
++++
P = \frac {A} {m} + (A * r)
++++

贷款 10 万，月利率 1%，期限 3 年（36 个月）。计算得出：

* 每月应还本金 2778 元，10 万 latexmath:[/] 36。
* 每月应还利息 1000 元，10 万 latexmath:[*] 0.01。
* 总还款数额约为 13.6 万元，其中利息约为 3.6 万元。

==== 折合年化利率


== 总结

等本等息所支付利息是最高的，其次是等额本息、等额本金。除了以上三种方式外，还有一种先息后本的还款方式，
利率很高，适用于短期贷款。先息后本的利息计算非常简单，固定本金与固定利率，计算出每个月的固定应还款数额，
期限到期后，一并归还本金。
根据个人经济情况选择适合自己的还款方式。

== 延伸阅读

* https://www.moneyhero.com.hk/blog/zh/月平息-低唔一定抵-實際年利率-apr-最實際[月平息利息及年利率計算]
* https://www.moneyhero.com.hk/blog/zh/提早還款有著數-貸款前要明白利息的78法則[贷款利息 78 法则]

